# Generated by Django 5.2.7 on 2026-03-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalencounter',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='subjective',
            field=models.TextField(blank=True, verbose_name='Subjetivo'),
        ),
    ]
