# Generated by Django 5.2.7 on 2026-03-10 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_clinicalencounter_diagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='Diagnostico sugerido')),
                ('subjective', models.TextField(blank=True, verbose_name='Subjetivo sugerido')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo sugerido')),
                ('assessment', models.TextField(blank=True, verbose_name='Evaluacion sugerida')),
                ('plan', models.TextField(blank=True, verbose_name='Plan sugerido')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='clinical.clinicalnotetemplate'),
        ),
    ]
