# Generated by Django 5.2.7 on 2026-03-10 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_clinicalnotetemplate_clinicalencounter_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalnotetemplate',
            options={'ordering': ['name', '-version']},
        ),
        migrations.AddField(
            model_name='clinicalnotetemplate',
            name='category',
            field=models.CharField(blank=True, max_length=60, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='clinicalnotetemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='clinicalnotetemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='clinical_template_name_version_unique'),
        ),
    ]
