# Generated by Django 5.2.7 on 2026-03-10 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_diagnosiscatalogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('LAB', 'Laboratorio'), ('IMAGE', 'Imagen'), ('PROCEDURE', 'Procedimiento'), ('MEDICATION', 'Medicacion'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Rutina'), ('URGENT', 'Urgente'), ('STAT', 'Inmediata')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('instructions', models.TextField(blank=True, verbose_name='Indicaciones')),
                ('result_notes', models.TextField(blank=True, verbose_name='Resultado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinical.clinicalencounter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
    ]
