[project]
name = "onne360"
version = "0.1.0"
description = ""
authors = [
    {name = "Alexander",email = "alexander.fran2023@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "django (>=5.2.7,<6.0.0)",
    "django-tenants (>=3.6,<4.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "gunicorn (>=25.0.1,<26.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

