# Generated by Django 5.2.7 on 2026-03-10 20:39

from django.db import migrations, models


def assign_membership_roles(apps, schema_editor):
    TenantMembership = apps.get_model('tenants', 'TenantMembership')
    TenantMembership.objects.filter(is_admin=True).update(role='ADMIN')
    TenantMembership.objects.filter(is_admin=False).update(role='STAFF')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('CLINICAL', 'Clinico'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
        migrations.RunPython(assign_membership_roles, migrations.RunPython.noop),
    ]
